//if[SQUAWK]
public class suite0 {

    private static final String __SUITE_CLASSES__ =
           "com/sun/javacard/impl/AppletInfo"
        + " com/sun/javacard/impl/AppletMgr"
        + " com/sun/javacard/impl/AppTableEntry"
        + " com/sun/javacard/impl/ComponentInfo"
        + " com/sun/javacard/impl/Constants"
        + " com/sun/javacard/impl/CryptoInit"
        + " com/sun/javacard/impl/Errors"
        + " com/sun/javacard/impl/GarbageCollector"
        + " com/sun/javacard/impl/NativeMethods"
        + " com/sun/javacard/impl/PackageEntry"
        + " com/sun/javacard/impl/PackageMgr"
        + " com/sun/javacard/impl/PackedBoolean"
        + " com/sun/javacard/impl/PrivAccess"
        + " java/io/IOException"
        + " java/lang/ArithmeticException"
        + " java/lang/ArrayIndexOutOfBoundsException"
        + " java/lang/ArrayStoreException"
        + " java/lang/ClassCastException"
        + " java/lang/Exception"
        + " java/lang/IndexOutOfBoundsException"
        + " java/lang/NegativeArraySizeException"
        + " java/lang/NullPointerException"
        + " java/lang/Object"
        + " java/lang/ObjectAssociation"
        + " java/lang/RuntimeException"
        + " java/lang/SecurityException"
        + " java/lang/Throwable"
        + " java/lang/VMExtension"
        + " java/lang/Thread"
        + " java/lang/Monitor"
        + " java/lang/Suite"
        + " java/rmi/Remote"
        + " java/rmi/RemoteException"
        + " javacard/framework/AID"
        + " javacard/framework/APDU"
        + " javacard/framework/APDUException"
        + " javacard/framework/Applet"
        + " javacard/framework/CardException"
        + " javacard/framework/CardRuntimeException"
        + " javacard/framework/Dispatcher"
        + " javacard/framework/ISO7816"
        + " javacard/framework/ISOException"
        + " javacard/framework/JCSystem"
        + " javacard/framework/MultiSelectable"
        + " javacard/framework/OwnerPIN"
        + " javacard/framework/PIN"
        + " javacard/framework/PINException"
        + " javacard/framework/Shareable"
        + " javacard/framework/SystemException"
        + " javacard/framework/TransactionException"
        + " javacard/framework/UserException"
        + " javacard/framework/Util"
        + " javacard/framework/service/BasicService"
        + " javacard/framework/service/CardRemoteObject"
        + " javacard/framework/service/Dispatcher"
        + " javacard/framework/service/RemoteService"
        + " javacard/framework/service/RMINativeMethods"
        + " javacard/framework/service/RMIService"
        + " javacard/framework/service/SecurityService"
        + " javacard/framework/service/Service"
        + " javacard/framework/service/ServiceException"
        + " javacard/security/AESKey"
        + " javacard/security/Checksum"
        + " javacard/security/CryptoException"
        + " javacard/security/DESKey"
        + " javacard/security/DSAKey"
        + " javacard/security/DSAPrivateKey"
        + " javacard/security/DSAPublicKey"
        + " javacard/security/ECKey"
        + " javacard/security/ECPrivateKey"
        + " javacard/security/ECPublicKey"
        + " javacard/security/Key"
        + " javacard/security/KeyAgreement"
        + " javacard/security/KeyBuilder"
        + " javacard/security/KeyPair"
        + " javacard/security/MessageDigest"
        + " javacard/security/PrivateKey"
        + " javacard/security/PublicKey"
        + " javacard/security/RandomData"
        + " javacard/security/RSAPrivateCrtKey"
        + " javacard/security/RSAPrivateKey"
        + " javacard/security/RSAPublicKey"
        + " javacard/security/SecretKey"
        + " javacard/security/Signature"
        + " javacardx/crypto/Cipher"
        + " javacardx/crypto/KeyEncryption";

    private static final String __SUITE_FLAGS__ = "reflective";
}

