//J2C:cno.c **DO NOT EDIT THIS FILE**
/*
 * Copyright 1994-2002 Sun Microsystems, Inc. All Rights Reserved.
 *
 * This software is the proprietary information of Sun Microsystems, Inc.
 * Use is subject to license terms.
 */

/*IFJ*/package com.sun.squawk.vm;
/*IFJ*/public final class CNO {
//IFC//#undef NULL

    public final static char
        /* Squawk specification types */
        NULL                 = 0,
        OBJECT               = 1,
        STRING               = 2,
        THROWABLE            = 3,
        CLASS                = 4,
        PRIMITIVE            = 5,
        VOID                 = 6,
        BOOLEAN              = 7,
        BYTE                 = 8,
        CHAR                 = 9,
        SHORT                = 10,
        INT                  = 11,
        LONG                 = 12,
        LONG2                = 13,
///*if[FLOATS]*/
        FLOAT                = 14,
        DOUBLE               = 15,
        DOUBLE2              = 16,
///*end[FLOATS]*/
        OBJECT_ARRAY         = 17,
        STRING_ARRAY         = 18,
        BOOLEAN_ARRAY        = 19,
        BYTE_ARRAY           = 20,
        CHAR_ARRAY           = 21,
        SHORT_ARRAY          = 22,
        INT_ARRAY            = 23,
        LONG_ARRAY           = 24,
///*if[FLOATS]*/
        FLOAT_ARRAY          = 25,
        DOUBLE_ARRAY         = 26,
///*end[FLOATS]*/

        /* Section of class numbers reserved in the spec */

        STRING_OF_BYTES      = 27,  /* Small strings. */
        STRING_OF_SYMBOLS    = 28,  /* Symbol strings. */
        RESERVED3            = 29,
        RESERVED4            = 30,

        FIRST_IMPLICIT_TYPE  = 1,
        LAST_IMPLICIT_TYPE   = 30,

        FIRST_PRIMITIVE_TYPE = BOOLEAN,
        LAST_PRIMITIVE_TYPE  = 16, /* DOUBLE2 */

        /* Squawk implementation specific types */
        LOCAL                = LAST_IMPLICIT_TYPE + 1,  /* Slot in stack chunk structure.   */
        GLOBAL               = LAST_IMPLICIT_TYPE + 2,  /* Slot in class state structure.   */
        LOCAL_ARRAY          = LAST_IMPLICIT_TYPE + 3,  /* Stack chunk structure.           */
        GLOBAL_ARRAY         = LAST_IMPLICIT_TYPE + 4,  /* Class state structure.           */
        GLOBAL_ARRAYARRAY    = LAST_IMPLICIT_TYPE + 5,  /* Table of class state structures. */



        FIRST_IMPL_TYPE      = LOCAL,
        LAST_IMPL_TYPE       = GLOBAL_ARRAYARRAY;

    public final static String[] IMPLICIT_PROXY_NAMES = {
        /* Squawk specification types */
        "**Unused**",
        "java.lang.Object",
        "java.lang.String",
        "java.lang.Throwable",
        "java.lang.Class",
        "java.lang._primitive_",
        "java.lang._void_",
        "java.lang._boolean_",
        "java.lang._byte_",
        "java.lang._char_",
        "java.lang._short_",
        "java.lang._int_",
        "java.lang._long_",
        "java.lang._long2_",
        "java.lang._float_",
        "java.lang._double_",
        "java.lang._double2_",
        "[java.lang.Object",
        "[java.lang.String",
        "[java.lang._boolean_",
        "[java.lang._byte_",
        "[java.lang._char_",
        "[java.lang._short_",
        "[java.lang._int_",
        "[java.lang._long_",
        "[java.lang._float_",
        "[java.lang._double_",
        "java.lang.StringOfBytes",
        "java.lang.StringOfSymbols",
        "java.lang.Reserved3",
        "java.lang.Reserved4",

        /* Squawk implementation specific types */
        "java.lang._local_",
        "java.lang._global_",
        "[java.lang._local_",
        "[java.lang._global_",
        "[[java.lang._global_"
    };
/*IFJ*/}
