echo Compiling jcard3....
java -jar build.jar jcard3
echo Done compiling
echo Translating...
java -jar build.jar translate -cp translator/classes:jcard3/classes -comments -o temp/oursuite.bin -O -format bin @vmtest
echo Done translating
echo Romizing...
java -jar build.jar romize -format bin -growrom -image temp/vmtest.image temp/jcard3.bin temp/oursuite.bin
echo Done romizing
echo Trying to execute...
java -jar build.jar squawk -Ximage:temp/vmtest.image -Xstats com.sun.squawk.vmtest.VMTest
echo DONE
